### ISSUE TITLE
Website Rewrite

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#10]
This issue is to [rewrite the website](https://github.com/capstone-coal/capstone-coal.github.io/issues/6#issuecomment-284128901) from scratch.

**Comment by ghost** [comment]
I have committed my contributions to a [new root branch](https://github.com/browtayl/capstone-coal.github.io/tree/ISSUE-10-Website-Rewrite) on my personal repository with `git checkout --orphan`. By design this will clobber all of the commits currently in `master`.

You may [preview the site](http://browtayl.github.io/capstone-coal.github.io) on my personal repo. Please review the code, the content, and the theme and suggest changes as necessary.

# Note

I had to follow [these instructions](https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908) and change a few links to serve the preview correctly from my personal site. I have added some fake blog posts with filler text which you can ignore. You can [compare](https://github.com/browtayl/capstone-coal.github.io/compare/browtayl:ISSUE-10-Website-Rewrite...gh-pages) the feature branch `ISSUE-10-Website-Rewrite` with the preview branch `gh-pages` to see exactly what differs between my commits and the preview.

# Done

I have implemented a simple Bootstrap/Jekyll template with a shared header and footer. The **home page** contains a carousel with data visualizations, an overview of our project, and links to documentation, blog posts, and team info. The **docs page** includes information on dependencies, installation, usage, and further reading. The **blog page** displays excerpts from blog posts in reverse chronological order. Each **blog post** is formatted with a common layout. The **team page** describes the senior capstone project, lists team members, and provides contact information. I used the capstone-coal avatar from GitHub to create the favorites icon.

# Todo

I am currently drafting **blog posts** that link to our fall and winter reports and presentations, sketches and other research efforts, the GDAL rotation bug fix, and our Python package. I believe this is the best way to incorporate our works in progress into the website. These could be tracked in separate issues if desired.

I still need to add a **wiki page** about how to edit the site and add posts. Editing the site is best accomplished by running `jekyll serve` locally. Posts can be drafted in the `_drafts` folder and published in the `_posts` folder. Jekyll uses special metadata sections for building the site.

The **docs** page will need to be updated with actual installation and usage instructions.

# More

The default **style** is meant to be utilitarian, but it could be made prettier if desired.

We may need to ensure that the logos do not run afoul of [JPL](https://www.jpl.nasa.gov/imagepolicy/) and [OSU](http://communications.oregonstate.edu/brand/visual-identity/logos) **branding** policies.

It would be possible to indicate the **active link** in the navbar with a bit of JS and/or CSS, however the site is perfectly functional without this.

I have not added a "fork me on GitHub" **ribbon**, but this would be super easy.

More **metadata** can be added to the blog posts by using [Liquid variables](http://jekyllrb.com/docs/variables/).

One thing that I would argue against implementing is blog **comment** functionality. Jekyll static sites are not very well suited to comments, although I have heard of people implementing a backend server that commits these to the repo. Some use third-party comment hosting services such as [Disqus](https://disqus.com/), but these can have [privacy implications](https://en.wikipedia.org/wiki/Disqus). In my experience, moderating public comments can be an administrative nightmare. I recommend that we consider the blog to be more of a news page and solicit feedback directly via email or GitHub. However, comment functionality can of course be implemented given additional development time.

**Comment by ghost** [comment]
@lewismc @kwhitehall @heidiaclayton I [can't open](https://github.com/capstone-coal/capstone-coal.github.io/compare/master...browtayl:ISSUE-10-Website-Rewrite?expand=1) a pull request because I have implemented the changes in a new root branch. You may review my code in [this branch](https://github.com/browtayl/capstone-coal.github.io/tree/ISSUE-10-Website-Rewrite), leave your comments here, and I can manually clobber master when the changes are approved.

**Comment by ghost** [comment]
The hypercube screenshot was generated in the `ipython` shell with commands similar to these:

    import spectral
    img = spectral.open_image('/media/study/OSU/winter17/cs462/data/AVNG_2015_data_distribution/L2/ang20150422t163638_rfl_v1e/ang20150422t163638_corr_v1e_img.hdr')
    spectral.view_cube(img[2100:2700,115:700,290:320])

The most interesting spectral features occur between bands 290 and 320.

**Comment by lewismc** [comment]
Excellent, absolutely excellent. The site looks brilliant. Thank you for this.

**Comment by ghost** [comment]
@lewismc Pushed to live [as requested](https://groups.google.com/d/msg/coal-capstone/u9zLBhH88EA/D9f1vd-nBQAJ).

I can either continue development pertaining to this issue in the branch `ISSUE-10-Website-Rewrite` and submit pull requests, or I can close this issue and file new ones to address the TODOs.

**Comment by lewismc** [comment]
Please close and we can file new issues in branch pull requests. Great job, honestly.
