### ISSUE TITLE
update Xiaomei's bio

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#15]
@lewismc in today's meeting some errors were discovered in @xiaomei7's bio on the [team page](https://capstone-coal.github.io/team):

* finance major, not accounting
* cs major, not minor
* no email address

this issue is to update the bio with accurate information. please submit a pull request with desired changes [as requested](https://groups.google.com/d/msg/coal-capstone/u9zLBhH88EA/uanuR9nRBQAJ).

**Comment by xiaomei7** [comment]
#20

**Comment by ghost** [comment]
merged and closed.
