### ISSUE TITLE
Augment README with local build instructions

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#22]
@browtayl can you kindly augment the README with the instructions for how to build this site locally? Thank you and sorry for the PITA request.

**Comment by ghost** [comment]
no problem. issue https://github.com/capstone-coal/capstone-coal.github.io/issues/12 already exists to document this in the wiki.

**Comment by ghost** [comment]
in the meantime, check out the documentation on [`jekyll serve`](http://jekyllrb.com/docs/usage/). there shouldn't be too much more to it than that.

**Comment by ghost** [comment]
@lewismc implemented in pull https://github.com/capstone-coal/capstone-coal.github.io/pull/23.
