### ISSUE TITLE
Consider Adding Case Study Data

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#28]
Currently the website documents the library but does not discuss our New Mexico case study. It could be added to a blog post or as its own page. There are already plenty of screenshots in Google Drive.

**Comment by ghost** [comment]
Assigning to @lewismc for feedback and to reassign as necessary.

**Comment by ghost** [comment]
The [GIS bundle](https://github.com/capstone-coal/pycoal/issues/93#issuecomment-303694434) contains all of the relevant data files. It would be possible to write a blog post linking to that and including some of the aforementioned screenshots.

**Comment by lewismc** [comment]
Yes, once the Glacier index updates, we can provide a link and a processing time. Typically it will be days. If anyone needs it sooner, I can move it to s3 OK.

**Comment by ghost** [comment]
Unassigning myself since I am not working on this right now. It is arguably in all of our interests to document the case study on the website somewhere, so I'll let you know if/when I feel like writing something up.

**Comment by lewismc** [comment]
I've documented all of this within https://github.com/capstone-coal/pycoal/pull/113 the only dataset we need to add is the NHD which can be manually downloaded by the user at ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Hydrography/NHD/State/HighResolution/Shape/
Additionally we need to link to this from the Website documentation.

**Comment by ghost** [comment]
The final report and case study data was added and documented [on the blog](https://capstone-coal.github.io/2017/08/25/final-report-gis-bundle.html). This is probably enough publicity considering we are awaiting ground truth verification of the case study data. The data sources are also documented [on the website](https://capstone-coal.github.io/docs#downloading). NHD is a subset of TNM so it is possible but not strictly necessary to link directly to it. In general I would expect it to be the end user's responsibility to find the applicable dataset for their application. I will go ahead and close this issue in light of these points, however it can be reopened or refiled if additional documentation or discussion is desired.

**Comment by ghost** [comment]
Usage was also documented in the `pycoal` [Examples](https://github.com/capstone-coal/pycoal/tree/master/examples).
