### ISSUE TITLE
Add OSU EECS News Blog Post

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#30]
Rachel from OSU recently posted another blog for us over on the OSU EECS News Blog
We should link to the post in our own blog
http://blogs.oregonstate.edu/eecsnews/2017/07/28/senior-design-team-wins-national-award/

**Comment by ghost** [comment]
I am still going to do this and back-date the article to keep things in order if that's alright. The blog page is filling out nicely despite my writer's block on this issue.

**Comment by lewismc** [comment]
lol no problems

**Comment by ghost** [comment]
merged and closed: https://github.com/capstone-coal/capstone-coal.github.io/pull/39
