### ISSUE TITLE
Fix Docs Typos

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#31]
Just noticed a couple improvements that should be made to the [Docs](https://capstone-coal.github.io/docs) page:

* Specify that Debian 8 was used to build QGIS. Debian 9.1 was recently [released](https://www.debian.org/News/2017/20170722) which I plan to use for future development and document accordingly.
* The [code](
https://github.com/capstone-coal/capstone-coal.github.io/blob/8a98d72ebb90d39b0e85adad233bec5437b44cc7/docs.html#L178) in the usage docs uses an undefined variable `test_image_name` which should probably be `input_filename`.

**Comment by lewismc** [comment]
Thanks for reporting @browtayl I just fixed
