### ISSUE TITLE
Follow Up on Improving GDAL/QGIS Installation Instructions

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#45]
This issue is to look into improving the GDAL/QGIS installation instructions [on the website](https://capstone-coal.github.io/docs#gdal) as discussed in the originally misfiled [`pycoal` issue 116](https://github.com/capstone-coal/pycoal/issues/116). Commit [`4504f67`](https://github.com/capstone-coal/capstone-coal.github.io/pull/43/commits/4504f67d6508f4a211a95c7599142a6bacb1d016) was reverted by commit [`a980eff`](https://github.com/capstone-coal/capstone-coal.github.io/commit/a980effdca889e5d287ba318e9faedd57faf7da6) because the official version of QGIS is currently out of date. Recommend leaving unassigned until either the official version of QGIS can be verified to incorporate the rotation patch or a cross-platform installation procedure can be devised.

**Comment by bdegley4789** [comment]
Thanks for moving this issue to the website @browtayl 
We discussed this issue in our meeting today. I plan to keep working on it. It seems like it is just something I have done wrong on my system, probably an issue with my path, installing an old version of gdal in frameworks or building an old version of gdal. I will update the instructions with a working solution as soon as I find one

**Comment by ghost** [comment]
Oh cool, then I'll set you as the assignee and let you take over. Dealing with all of these libraries can be a real pain, so I'm not surprised there have been issues getting it to work. The original instructions were biased towards GNU/Linux because the majority of last year's team used Debian or Ubuntu and supporting multiple platforms was not part of our requirements.

If patching GDAL and QGIS becomes a regular problem—quite possible when extending a free software library to support a proprietary image format—then it would be tempting to just build something that can be redistributed rather than have end-users compile stuff. But that would be a separate issue.

**Comment by bdegley4789** [comment]
I fixed all the trace errors with gdal I had when running environmental correlation in the Alpha release video. As you can see in the photos environmental correlation runs without any trace errors or warnings. And the FlowLines are now clearly visible. In pull request #47 I updated the original installation instructions with what fixed the problems on my system. 
![environment_run](https://user-images.githubusercontent.com/25111791/37025935-d5fc8ea8-20e1-11e8-9454-60fc46da4f92.png)
![environmental_correlation_qgis](https://user-images.githubusercontent.com/25111791/37025945-ddf2260e-20e1-11e8-8311-1b9de9d4bd22.png)

**Comment by bdegley4789** [comment]
I still think we should refer users to the latest version of QGIS and GDAL on their websites. I guess with GDAL we could have it be optional to get the 2.2 branch to fix the rotational error. However, @browtayl  it looks like the Windows version of QGIS displays the image correctly rotated, as it is displayed in the posters but the mac OS X version of QGIS which I used in the demo video seems to always display the QGIS images vertically. I am using both of these at 2.18 QGIS and 2.2.3 GDAL. I made a note about this for mac users in my pull request for updating QGIS and GDAL installation instructions.

**Comment by bdegley4789** [comment]
On Windows qgis 2.18
![windows_qgis](https://user-images.githubusercontent.com/25111791/37026133-5696ab66-20e2-11e8-9b99-79d2ce0ea8fb.png)

**Comment by bdegley4789** [comment]
On Mac qgis 2.18
![mac_qgis](https://user-images.githubusercontent.com/25111791/37026157-68296b48-20e2-11e8-8360-862fc65d4141.png)

**Comment by ghost** [comment]
That's a really interesting finding, somewhat unexpected. The QGIS website does not provide very much detail on what versions they use to build the software, so this process of trial and error is genuinely useful.

I would agree this makes a stronger case for linking to the official release, maybe with the caveat that the Mac and maybe GNU/Linux versions haven't caught up with the rotation fix yet as noted in your pull request.

The rotation fix is relatively cosmetic in the QGIS use case because it only affects how the data is displayed, though it becomes important when looking at more than one flightline or data set. It probably shouldn't be optional when installing GDAL for processing because in that case the rotation header doesn't get set correctly and then the environmental correlation breaks.

Let's see if @lewismc has any comments on this and move forward with integrating the changes. We can leave specific code review in pull https://github.com/capstone-coal/capstone-coal.github.io/pull/47. In the meantime thanks for the detailed review of this issue!

**Comment by lewismc** [comment]
If what has been committed in https://github.com/capstone-coal/capstone-coal.github.io/pull/49 is good then I am happy to progress. This has been a PITA, but I am glad that we are by it now and can move on to actually improving the toolkit again. Thanks.
