### ISSUE TITLE
fix org website link

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#5]
The link to the website on our [GitHub Organization](https://github.com/capstone-coal) currently points to [http://capstone-coal.github.io/coal](http://capstone-coal.github.io/coal) but it should point to [https://capstone-coal.github.io/](https://capstone-coal.github.io/). Assigning to @lewismc because I don't seem to have permissions to change it.

**Comment by lewismc** [comment]
Fixed thanks
