### ISSUE TITLE
USGS Spectral Library Version 7 documentation

### ISSUE THREAD

**Issue by bdegley4789** [capstone-coal/capstone-coal.github.io#52]
Add documentation for pycoal users to use the convolved envi files for USGS Spectral Library Version 7

**Comment by bdegley4789** [comment]
@lewismc I'm having trouble finding the code to edit to include information on the conversion classes I created in mineral.py to get them into readthedocs https://pycoal.readthedocs.io/en/latest/mineral.html

**Comment by lewismc** [comment]
Here you go 
https://github.com/capstone-coal/pycoal/blob/master/docs/source/mineral.rst
You can build the documents locally so you can try it out before submitting a PR

**Comment by bdegley4789** [comment]
I tried doing the same thing that was done for the AsterConversion class https://github.com/bdegley4789/pycoal/blob/master/docs/source/mineral.rst
I'm not sure why it says module 'pycoal.mineral' has no attribute 'SpectalToAsterFileFormat' 
```
/Users/bryceegley/Desktop/pycoal/docs/source/mineral.rst:30: WARNING: autodoc: failed to import class 'SpectalToAsterFileFormat' from module 'pycoal.mineral'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/bryceegley/anaconda3/lib/python3.6/site-packages/sphinx/util/inspect.py", line 169, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pycoal.mineral' has no attribute 'SpectalToAsterFileFormat'
```

**Comment by lewismc** [comment]
push what you have I will look at it tomorrow, thanks go to bed.

**Comment by bdegley4789** [comment]
ok will do. I pushed it to my fork https://github.com/bdegley4789/pycoal/blob/master/docs/source/mineral.rst
