### ISSUE TITLE
jekyll blog

### ISSUE THREAD

**Issue by ghost** [capstone-coal/capstone-coal.github.io#6]
this issue is for implementing the blog on the website.

@xiaomei7 and i discussed the jekyll documentation:
https://jekyllrb.com/docs/structure/
https://jekyllrb.com/docs/configuration/
https://jekyllrb.com/docs/frontmatter/
https://jekyllrb.com/docs/posts/

an example of a (partial) jekyll blog can be found on an old revision of my website:
https://github.com/browtayl/browtayl.github.io/tree/e64fb99e6114e8f30f1151d955e0a9cb5f52865f

**Comment by lewismc** [comment]
Hi @xiaomei7 this is a piece of cake to implement, please see
https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/
It would be nice to get this updated and.

**Comment by lewismc** [comment]
Hi @xiaomei7 is there anything blocking you here? We need to get this blog moving quickly as I am trying my best to showcase the project to people in order to grow interest. If your not able to complete the task for this week then I will take it on and you can work on other tasks. Please let me know.
Thanks

**Comment by ghost** [comment]
As stated in today's meeting  with @lewismc, our goal is to have a functional, informative, and attractive site by 2017-03-10.

The website is currently unusable. Requests for improvement, offers of assistance, and complaints have been made repeatedly on the mailing list, GitHub issues, and meetings, but these have been largely ignored. The team meetings we arranged to address this were skipped, and no meaningful progress has been made for weeks.  @xiaomei7 told us today that she was unable or unwilling to contribute because she is "really busy".

Therefore I hereby take responsibility for the website. It is my intention to rewrite it from scratch. I am going to close currently open issues or reassign them to myself and submit a pull request when ready. The team apologizes for the delay.

**Comment by ghost** [comment]
For the record, I have now taken responsibility for all three modules that @xiaomei7 originally agreed to implement. I will be informing our TA @narayave and our professors as necessary.

**Comment by ghost** [comment]
Addressed in Issue https://github.com/capstone-coal/capstone-coal.github.io/issues/10. Closed.

**Comment by lewismc** [comment]
This is disappointing. Thanks for the update. Several opportunities and a lot of patience has been shown.
