### ISSUE TITLE
Implement page for all team members

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#7]
Hi @xiaomei7 can you please implement a page which shows each of the team off?
Something like the following
https://speckyboy.com/50-webpage-layouts-showcasing-company-teams-employees/
Thank you

**Comment by xiaomei7** [comment]
Hi, @lewismc, I have been work on the Jekyll for last several days, and I just finished the overhaul of the website and added the (hope it works) blog page. I leave the "People" menu unfinished since we need to show each member of our team rather than just links to our GitHub pages. I think I would have time to do the page like as showed this weekend.

**Comment by lewismc** [comment]
Great @xiaomei7 thank you. Feel free to use this issue tracker to provide updates with your progress. Thank you.

**Comment by lewismc** [comment]
Can you send a PR for the blog issue so i can review? Thank you

**Comment by xiaomei7** [comment]
Sorry, @lewismc it seems like I can't create a pull request because I commit directly to the master branch.

I test on the blog again this morning, and it appears to work as expected. So, I would be started to work on the styling as well this weekend.

**Comment by lewismc** [comment]
Can you please revert the commit to the Website and submit a pull request? The styling is all off and we have a workflow for how these things should be done
https://github.com/capstone-coal/pycoal/wiki/PyCOAL-Development-Workflow
If you need me or someone else to revert the commit to master branch then let one of us know. Thank you.

**Comment by xiaomei7** [comment]
Hi, @lewismc, here is the pull request #8

**Comment by ghost** [comment]
I am going to address this per issue https://github.com/capstone-coal/capstone-coal.github.io/issues/6. Closed.
